language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "vek5Lq9IirLdj8RL+fdQI3iUSMuxarmklNgpVwD2hKNETgBKAZ8ReDEoV+X7MfMVAWrkh1i328J4DurMxCFyw9Y39ZJ0Js1Y0vcUAYlFI/EgTHiCMjIueLAfZD45+xlqGdmzqaF50+Wjii5CytDPB2ZPmFiVAuxFcbcKFTnVm+N+deBMdj3w9cb8bnP1DOWafaixnf1YzE+Th7qufJrKLbsKdP0tfZ1njpzQFzskO7OWmGCObJPKfbk/KmBY8Eks30V5HR6VlHGFTvXXlT9fh+xYIikEkaZSAtPko09DoMK9NSLKi04u1deVxTgvLWTbsC0Iq/a89IH/S3wiUX62HZd8ppwm+qkZ6qToGk1aJbCFDdfZudEEiDxgCFXNWywtlnN1Xyn7DRKecgTdG+Xh0hEKC4HOP5rXsMGFAfm7UKRIpmawGANT5IsygNzHSI/sK+l4Mtny+FvHd8/LWSybnWJ3KQzKTginnhkSi3lMLgYgeRak+2jNNDk5z1xV6Zkw1iI9IIv92nLrfQu4QoP4QYVJ3KaWxztIrRgmiM5YCZGuTwy48FC9OGSr1roMIxPh40cTAZtf2IeRE2ZNp87305cOM7FwN8IbW4ZDYZINw8/TKlFqTdX2pQgK+bAgAfny1josGR3jkYArYpJtPv0xmZ3Bg61Xlh2vXtLJrt8id5U="
