language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "CEKVMAy3+hI2bxNDudjojRIegKraGuHewPPVSvaq+s2Oy6VzLnQrH7tnDNfxjgRENhfbMSH1Yj2FGHy2y5QaLKRMgbEpa0QWYPMrjP9pP5PvtHIbiDwVPYlanZrCXWEo9CwLFJXPfiNoZqA5Uklkd6kkBgL79kvD0pxXXVP67xFqtn9cxryRkltYcO0rn6sLl1FPK3qRCO453XhXPlcFNAZZfUBThV2/Ckz+MOHE2/I/cdfQCI2fyuc1c3YEldxg4G6DT0YRTaJ2ZtMhf0GUIxhQZqO149Yy7heluOIsbno0AHzID98Cmb/eJDqy0G+izSBhTdoVAN3lsGaZGtnA34ampdI9WUS17dr1Be8IqvF8DBm5Dwe57IT0yZjTdOpI1wY170OuByVcD1p/sPuNujjNSWGbyouYFvn2DdVz/2DrqanruZVSkfsNquzep0GuGwdzEgV0ioiwTqKhs+/Hjwtz90O6vb9AOwWEt2+NPW9zk9LHaoDBemQGj4kdWk3RYsLskYeHTRQclvdRpXQE3phNhe+05t9kR2horG8R+TbLGJTEU8xd4OaChWv4qq6xpAQADy59M3ZC2++g1UuxGRsmByzcD/7uU8Bc8xkHRsKWoXnGwoiUmQia1MS8fpiKvgd3Elp9SMy4dA80d2AobHmF3NJNV98tYoRQSuKVlHY="