language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "FA+0L6mdCm760BIqtLcrArZRo7ZMoLXCkZrXBBhjIZgEKlhbQ7CiUxR8BSzPSQ0sX003WU9hfkxlJuXNA93quyDSDeDZpGP8GAoVwFd+s/BDgwuXkOavllKbUHXkB3Uj47Ft6QXjnVfkfiTntO2bYfRd4Y14rcJwlPlldOTRarUhvUbQ1kWuC9g0+hc0w4LENVVc5JvIdnMHsWny0M5yIH/quv9UWCzog9TwBtfOqjGsI8vh0+q36SliTD+8x5OSz9F04gC5aw9FhKXh5T29nyaiFOgcDJDZOgEyrfAWOxurEa4jJw2R8pQ8hj1Oq5XphiraOX1rTQyucXH6P+YrfaM/FS/bEaaVoDtmh6fgjRtDOg7FNn9l1rY/leXM18Gfgd8eXDDnIpyzTgwWNYpnNZXL1a+8Rec69sBRJysyC5VbdCKj6NiZiJWn1nnkCXId+0n+2ri163o8dzQNH6175t98MTNbPY7kPHBh2nMOXqlJilCiF/E8VpuHBD0TIxpeLQAncqIjkxJ2vrepriGKvovdFbEJukej7jHAoOgHtFNSA24+o+HBnDgwmEdTokMcsAlVSX0eT42bMWzo2//9WxJYp5IsL2b4gEQa2LgD+8kMRixJQPFizeqCOr2Ss5FfkwoQU4XRCsZJUiPwK/Qtj5WMjg9LhvhjEjA+Qgs60i8="