language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "QjZIqls9koo2ROPxbBYqfZ/ET+8WG94wm4Fq64Rz1SVlVqBKbkEijDIKH+TjHkn8wwmmy2AoA1okgBYpJQXPZL5turl2fsDeK+a5UFqU+qdeWlTw80wbVHKMJbLxDkcm2oUBfXxW9JYOqeUPY9Qc/oWx51BudGpyIO/+HILsPgP3ZodVaSopOPYoZCIxCTqcbBlioNtqwWa9XRBz/EIjbKIpk1iAR7YQBj/9W3WTzNwODBzFv/nSxGGLl2u7qQ/ljVaPURv1U240DFoLlrf1KqZClzymg7HSKNDERLNHpuF+tNBVIznSkEEjyBo5N6c5jmXFIp/uu1VvZj9Y7TCwJaJfvAzS5htnLQA/CZS2xFtX07YVJF7cPF72fWeM81gFWJgmsXzsSFAy3uUfsfCnJCvi+KR14IW65hEb1x/uOqe6dDzDT4704ZbFhp/aQDNyjfypCh4EAIaXGWeQQN5pIisNzhEiXIc/VrKJvdL5jSqsR8ocMePN7vtfJTEIoOZv1ghhCqkUw1yphHHc7M6fBFJin1Xnbl65uupYVU53Xp9IO3zzcbUWbQLTGAbIwzwJ0ZmMqBCVMTDXwEWiuFfOAqKXVKjfMPzn9tB+A/0ZHKa7xkvNFaQ5XVI2Gh/h06yfWGeNlMtJw1VFJk231mg6DX4f99pP6xlyoeeYkomPF90="