language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- ./ci/shim.js
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "STUNI6tOEw6YlpzuggJ5+yilIeCPNooZVt4z9HOEj5ucYGnIOVluLHjKDiJmZqi5XsejVUPr2upg/61FxywVpE01FeirIxXjZASgwPb5Z6NHxjQBQ7/2ixv2mNw0GIlwsSwmyrKHFsHNDZjl7XC+cc13jvRfu0FM0W0P+U6XvTi1fBeAaZ0T9/IrBCTix0bCvH9nEw+T3KU/qp2rISlOt8mFIDWLA1J5xdUpcxHNq4+czT8LVqpgnpf9yIML/DIKZWhZfLS1DpR7RbR9KMlhXPHBqwcph6Un5Y+1RKj/OLPaBtE+J4Oa6Ujsf5905bKC7+gSh1dBPE9wWyNM2SLRuRFjX5lbQKVBdzQcVNlFi7p3Q8bwOdQ8EGBlE285ezwSnx+9eXpwXMpKMBMZyxapWEP58j0p6ROwzGcBrrPvNUqu2whLeARJGVjZ7dHSI5zqBcTV7jTEirUhfaOy5V+db0WjDRmh8PudI7A8OIFTXhTcz1Rz62ZeiU0sS9i+nug66Dj7CaBxFtjb7CvG2Fx7JTLCW1Tet9jcpX/S7oN0RHGBc09T+4yCBX9520XelTD47qOd8u8reBXFCV6Mjj/GBxVl+zB0v4I3Zwa/AeKtMEIXNdrl5QfOHhapqW8WLzkF8Ez2qvQxXyuz/SOOLfcsm1yWyNcvMBJheKS5ds/wUKU="